server:
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: false
  base:
    address: ${SERVER_BASE_ADDRESS}

spring:
  application:
    name: urlific
logging:
  level:
    com.lunaticdevs: debug

secret:
  key: ${SECRET_KEY}